"""NM Now curated lineup — v2 (2026-08-23): all 414 Titan (cdnlive) channels.

The US block below is curated by hand (judgment calls in the comments). Everything
else is generated (see gen_intl.py) and grouped into region categories.

One row per channel: (ntv_name, number, display, short, category, epg_id).

`ntv_name` is the exact `channel_name` in NTV's /api/get-channels catalog (Titan server,
code=us). The builder looks the stream up by that key — if NTV renames a channel, the
build logs it as MISSING (channel dropped from that build) rather than guessing.

`epg_id` is the epg.pw XMLTV channel id. None = no schedule source; the channel still
publishes with a playable stream and the app fills its row with "No Program Information".

Numbers are stable labels, deliberately gappy (dropped channels free their number for
good). Categories are free-form ids matching the categories array we publish; `recents`
and `all` are reserved by the app and never used here.

Judgment calls worth remembering:
- ABC -> National Feed (464902), NBC -> NBC East Stream (465059), CBS -> CBS West
  (464830). epg.pw has no national FOX feed at all -> FOX stays unmapped.
- NESN -> NESN+ (496625): epg.pw carries only the overflow feed, not main NESN. A close
  schedule beats none.
- beIN SPORTS 1/2/3 dropped: "beIN SPORTS" (exact epg.pw twin 464754) covers the
  franchise; the numbered feeds are dup clutter with no US EPG twin.
- MLB team channels map to epg.pw's "MLB - <Team>" virtual channels — these carry the
  RSN schedule for that market.
- ESPN's catalog name is "ESPN+ USA"; displayed as plain "ESPN".
"""

Category = tuple[str, str, str]  # id, label, icon

CATEGORIES: list[Category] = [
    ("networks", "Networks", "networks"),
    ("news", "News", "news"),
    ("sports", "Sports", "sports"),
    ("entertainment", "Entertainment", "entertainment"),
    ("documentary", "Documentary", "documentary"),
    ("kids", "Kids", "kids"),
    ("premium", "Movies & Premium", "premium"),
    ("spanish", "Español", "spanish"),
] + [
    # International regions — generated numbering, see gen_intl.py for the bases.
    ("uk", "UK", "uk"),
    ("germany", "Germany & Austria", "germany"),
    ("france", "France", "france"),
    ("iberia", "Spain & Portugal", "iberia"),
    ("nordics", "Nordics", "nordics"),
    ("benelux", "Benelux", "benelux"),
    ("italy", "Italy", "italy"),
    ("cee", "Central & Eastern Europe", "cee"),
    ("greece", "Greece & Cyprus", "greece"),
    ("russia", "Russia", "russia"),
    ("turkey", "Turkey", "turkey"),
    ("latam", "Latin America", "latam"),
    ("canada", "Canada", "canada"),
    ("anz", "Australia & NZ", "anz"),
    ("mideast", "Middle East", "mideast"),
]

Row = tuple[str, str, str, str, str, str, str]  # ntv, number, display, short, category, epg_cc, epg_id

LINEUP: list[Row] = [
    # --- Networks 1xx ---
    ("ABC", "101", "ABC", "net", "networks", "US", "464902"),
    ("CBS", "102", "CBS", "cbs", "networks", "US", "464830"),
    ("NBC", "103", "NBC", "nbc", "networks", "US", "465059"),
    ("FOX", "104", "FOX", "fox", "networks", "US", ""),
    # --- News 2xx ---
    ("FOX News", "201", "FOX News", "fnc", "news", "US", "465372"),
    ("CNN", "202", "CNN", "cnn", "news", "US", "464857"),
    ("CNBC", "203", "CNBC", "cnbc", "news", "US", "464791"),
    # --- Sports, national 3xx ---
    ("ESPN+ USA", "301", "ESPN", "espn", "sports", "US", "465198"),
    ("ESPN 2", "302", "ESPN2", "esp2", "sports", "US", "465373"),
    ("ESPN News", "303", "ESPNews", "espn", "sports", "US", "465410"),
    ("ESPN U", "304", "ESPNU", "espu", "sports", "US", "465108"),
    ("FOX Sports 1", "305", "FS1", "fs1", "sports", "US", "465291"),
    ("beIN SPORTS", "306", "beIN Sports", "bein", "sports", "US", "464754"),
    ("Tennis Channel", "309", "Tennis Channel", "ten", "sports", "US", "465236"),
    ("MLB Network", "310", "MLB Network", "mlb", "sports", "US", "465239"),
    ("NBA TV", "311", "NBA TV", "nba", "sports", "US", "464912"),
    ("NFL Network", "312", "NFL Network", "nfl", "sports", "US", "465311"),
    ("NHL Network", "313", "NHL Network", "nhl", "sports", "US", "465348"),
    ("TUDN", "314", "TUDN", "tudn", "sports", "US", "465174"),
    ("FOX Soccer Plus", "315", "FOX Soccer Plus", "fsp", "sports", "US", "465214"),
    ("Willow Cricket", "316", "Willow Cricket", "wil", "sports", "US", "465010"),
    ("ACC Network", "317", "ACC Network", "acc", "sports", "US", "464879"),
    ("SEC Network", "318", "SEC Network", "sec", "sports", "US", "465266"),
    ("Marquee Sports Network", "319", "Marquee Sports", "marq", "sports", "US", "465271"),
    ("Space City Home Network", "320", "Space City", "schn", "sports", "US", "465220"),
    ("Monumental Sports Network", "321", "Monumental", "mon", "sports", "US", "465347"),
    ("CBS Sports Golazo", "322", "CBS Sports Golazo", "gol", "sports", "US", "562308"),
    ("WWE", "323", "WWE Network", "wwe", "sports", "US", "558129"),
    ("GOLF TV", "324", "GOLF TV", "golf", "sports", "US", ""),
    ("Astro Cricket", "325", "Astro Cricket", "astro", "sports", "US", ""),
    # --- Sports, regional 33x-36x ---
    ("MASN", "330", "MASN", "masn", "sports", "US", "465409"),
    ("MSG", "331", "MSG", "msg", "sports", "US", "465033"),
    ("NESN", "332", "NESN", "nesn", "sports", "US", "496625"),
    ("SportsNet New York", "333", "SNY", "sny", "sports", "US", "464777"),
    ("Yes Network", "334", "YES Network", "yes", "sports", "US", "496607"),
    ("Altitude", "335", "Altitude Sports", "alt", "sports", "US", "465288"),
    ("Chicago Sports Network", "336", "Chicago Sports Net", "chsn", "sports", "US", "465058"),
    ("Red Bull", "337", "Red Bull TV", "rbt", "sports", "US", ""),
    ("Arizona Diamondbacks", "340", "AZ Diamondbacks", "ari", "sports", "US", "465596"),
    ("Atlanta Braves", "341", "Atlanta Braves", "atl", "sports", "US", "465580"),
    ("Baltimore Orioles", "342", "Baltimore Orioles", "bal", "sports", "US", "465732"),
    ("Boston Red Sox", "343", "Boston Red Sox", "bos", "sports", "US", "465749"),
    ("Chicago Cubs", "344", "Chicago Cubs", "chc", "sports", "US", "465534"),
    ("Chicago White Sox", "345", "Chicago White Sox", "cws", "sports", "US", "465665"),
    ("Cincinnati Reds", "346", "Cincinnati Reds", "cin", "sports", "US", "465509"),
    ("Cleveland Guardians", "347", "Cleveland Guardians", "cle", "sports", "US", "465558"),
    ("Colorado Rockies", "348", "Colorado Rockies", "col", "sports", "US", "465569"),
    ("Detroit Tigers", "349", "Detroit Tigers", "det", "sports", "US", "465712"),
    ("Houston Astros", "350", "Houston Astros", "hou", "sports", "US", "465528"),
    ("Kansas City Royals", "351", "Kansas City Royals", "kc", "sports", "US", "465731"),
    ("Los Angeles Angels", "352", "Los Angeles Angels", "laa", "sports", "US", "465642"),
    ("Los Angeles Dodgers", "353", "Los Angeles Dodgers", "lad", "sports", "US", "465761"),
    ("Miami Marlins", "354", "Miami Marlins", "mia", "sports", "US", "465548"),
    ("Milwaukee Brewers", "355", "Milwaukee Brewers", "mil", "sports", "US", "465633"),
    ("Minnesota Twins", "356", "Minnesota Twins", "min", "sports", "US", "465598"),
    ("New York Mets", "357", "New York Mets", "nym", "sports", "US", "465547"),
    ("New York Yankees", "358", "New York Yankees", "nyy", "sports", "US", "465667"),
    ("Oakland Athletics", "359", "Oakland Athletics", "oak", "sports", "US", "465542"),
    ("Philadelphia Phillies", "360", "Philadelphia Phillies", "phi", "sports", "US", "465689"),
    ("Pittsburgh Pirates", "361", "Pittsburgh Pirates", "pit", "sports", "US", "465703"),
    ("San Diego Padres", "362", "San Diego Padres", "sd", "sports", "US", "465795"),
    ("San Francisco Giants", "363", "San Francisco Giants", "sf", "sports", "US", "465773"),
    ("Seattle Mariners", "364", "Seattle Mariners", "sea", "sports", "US", "465605"),
    ("St. Louis Cardinals", "365", "St. Louis Cardinals", "stl", "sports", "US", "465720"),
    ("Tampa Bay Rays", "366", "Tampa Bay Rays", "tb", "sports", "US", "465645"),
    ("Texas Rangers", "367", "Texas Rangers", "tex", "sports", "US", "465751"),
    ("Toronto Blue Jays", "368", "Toronto Blue Jays", "tor", "sports", "US", "465794"),
    # --- Entertainment 4xx ---
    ("TBS", "401", "TBS", "tbs", "entertainment", "US", "465285"),
    ("TNT", "402", "TNT", "tnt", "entertainment", "US", "465114"),
    ("USA Network", "403", "USA Network", "usa", "entertainment", "US", "465006"),
    ("truTV", "404", "truTV", "tru", "entertainment", "US", "464987"),
    ("Travel Channel", "405", "Travel Channel", "trvl", "entertainment", "US", "465186"),
    ("Hallmark", "406", "Hallmark Channel", "hall", "entertainment", "US", "465241"),
    ("Lifetime", "407", "Lifetime", "life", "entertainment", "US", "465290"),
    ("TLC", "408", "TLC", "tlc", "entertainment", "US", "464919"),
    ("BBC", "409", "BBC America", "bbc", "entertainment", "US", "465025"),
    ("BET", "410", "BET", "bet", "entertainment", "US", "464968"),
    ("TV ONE", "411", "TV One", "tvo", "entertainment", "US", "465208"),
    # --- Documentary 45x ---
    ("Discovery Channel", "451", "Discovery Channel", "disc", "documentary", "US", "465364"),
    ("History", "452", "History", "hist", "documentary", "US", "465176"),
    ("National Geographic", "453", "National Geographic", "natg", "documentary", "US", "465089"),
    # --- Kids 5xx ---
    ("Disney Channel", "501", "Disney Channel", "dis", "kids", "US", "465349"),
    ("Nickelodeon TV", "502", "Nickelodeon", "nick", "kids", "US", "465251"),
    ("Universal Kids", "503", "Universal Kids", "unik", "kids", "US", ""),
    # --- Premium 6xx ---
    ("HBO", "601", "HBO", "hbo", "premium", "US", "464745"),
    ("Cinemax", "602", "Cinemax", "cinx", "premium", "US", "464917"),
    ("Showtime", "603", "Showtime", "sho", "premium", "US", ""),
    ("MAX", "604", "MAX", "max", "premium", "US", ""),
    # --- Espanol 7xx ---
    ("Univision", "701", "Univision", "uni", "spanish", "US", "464782"),
    ("Telemundo", "702", "Telemundo", "tld", "spanish", "US", "464962"),
    ("NBC Universo", "703", "Universo", "univ", "spanish", "US", "465329"),
    ("ESPN Deportes", "704", "ESPN Deportes", "espd", "spanish", "US", "464949"),
    ("FOX Deportes", "705", "FOX Deportes", "fde", "spanish", "US", "465156"),
]

# --- International rows, GENERATED by `python -m nmnowfeed.gen_intl <catalog.json>` ---
# Regenerating renumbers from a fresh catalog — review as a rename diff, never blind-paste.
# epg_id is always "" here: the build resolves ids by name (matching.py) so an epg.pw or
# NTV rename heals on the next build. The epg_cc column is ALWAYS the catalog country —
# it is also the stream lookup key; epg.EPG_COUNTRIES decides who actually gets a file.
LINEUP_INTL: list[Row] = [
    # --- UK ---
    ("BBC Four", "801", "BBC Four", "bbc", "uk", "GB", ""),
    ("BBC One", "802", "BBC One", "bbc", "uk", "GB", ""),
    ("BBC Three", "803", "BBC Three", "bbc", "uk", "GB", ""),
    ("BBC Two", "804", "BBC Two", "bbc", "uk", "GB", ""),
    ("Channel 4", "805", "Channel 4", "chan", "uk", "GB", ""),
    ("Channel 5", "806", "Channel 5", "chan", "uk", "GB", ""),
    ("DAZN 1", "807", "DAZN 1", "dazn", "uk", "GB", ""),
    ("Euro Sport 1", "808", "Euro Sport 1", "euro", "uk", "GB", ""),
    ("Euro Sport 2", "809", "Euro Sport 2", "euro", "uk", "GB", ""),
    ("ITV 1", "810", "ITV 1", "itv", "uk", "GB", ""),
    ("ITV 2", "811", "ITV 2", "itv", "uk", "GB", ""),
    ("ITV 3", "812", "ITV 3", "itv", "uk", "GB", ""),
    ("ITV 4", "813", "ITV 4", "itv", "uk", "GB", ""),
    ("LaLiga TV", "814", "LaLiga TV", "lali", "uk", "GB", ""),
    ("Premier Sports 1", "815", "Premier Sports 1", "prem", "uk", "GB", ""),
    ("Premier Sports 2", "816", "Premier Sports 2", "prem", "uk", "GB", ""),
    ("Sky Sports Action", "817", "Sky Sports Action", "sky", "uk", "GB", ""),
    ("Sky Sports Arena", "818", "Sky Sports Arena", "sky", "uk", "GB", ""),
    ("Sky Sports Cricket", "819", "Sky Sports Cricket", "sky", "uk", "GB", ""),
    ("Sky Sports F1", "820", "Sky Sports F1", "sky", "uk", "GB", ""),
    ("Sky Sports Football", "821", "Sky Sports Football", "sky", "uk", "GB", ""),
    ("Sky Sports Golf", "822", "Sky Sports Golf", "sky", "uk", "GB", ""),
    ("Sky Sports Main Event", "823", "Sky Sports Main Event", "sky", "uk", "GB", ""),
    ("Sky Sports Mix", "824", "Sky Sports Mix", "sky", "uk", "GB", ""),
    ("Sky Sports Premier League", "825", "Sky Sports Premier League", "sky", "uk", "GB", ""),
    ("Sky Sports Racing", "826", "Sky Sports Racing", "sky", "uk", "GB", ""),
    ("Sky Sports Tennis", "827", "Sky Sports Tennis", "sky", "uk", "GB", ""),
    ("TNT Sports 1", "828", "TNT Sports 1", "tnt", "uk", "GB", ""),
    ("TNT Sports 2", "829", "TNT Sports 2", "tnt", "uk", "GB", ""),
    ("TNT Sports 3", "830", "TNT Sports 3", "tnt", "uk", "GB", ""),
    ("TNT Sports 4", "831", "TNT Sports 4", "tnt", "uk", "GB", ""),
    ("TNT Sports 5", "832", "TNT Sports 5", "tnt", "uk", "GB", ""),
    ("TNT Sports 6", "833", "TNT Sports 6", "tnt", "uk", "GB", ""),
    ("TNT Sports 8", "834", "TNT Sports 8", "tnt", "uk", "GB", ""),
    ("Viaplay Sports 1", "835", "Viaplay Sports 1", "viap", "uk", "GB", ""),
    ("Viaplay Sports 2", "836", "Viaplay Sports 2", "viap", "uk", "GB", ""),
    # --- Germany & Austria ---
    ("DAZN 1", "841", "DAZN 1", "dazn", "germany", "DE", ""),
    ("DAZN 2", "842", "DAZN 2", "dazn", "germany", "DE", ""),
    ("Das Erste", "843", "Das Erste", "das", "germany", "DE", ""),
    ("RTL", "844", "RTL", "rtl", "germany", "DE", ""),
    ("Sky Sport 1", "845", "Sky Sport 1", "sky", "germany", "DE", ""),
    ("Sky Sport 2", "846", "Sky Sport 2", "sky", "germany", "DE", ""),
    ("Sky Sport 3", "847", "Sky Sport 3", "sky", "germany", "DE", ""),
    ("Sky Sport 4", "848", "Sky Sport 4", "sky", "germany", "DE", ""),
    ("Sky Sport 5", "849", "Sky Sport 5", "sky", "germany", "DE", ""),
    ("Sky Sport Bundesliga 1", "850", "Sky Sport Bundesliga 1", "sky", "germany", "DE", ""),
    ("Sky Sport Bundesliga 10", "851", "Sky Sport Bundesliga 10", "sky", "germany", "DE", ""),
    ("Sky Sport Bundesliga 2", "852", "Sky Sport Bundesliga 2", "sky", "germany", "DE", ""),
    ("Sky Sport Bundesliga 3", "853", "Sky Sport Bundesliga 3", "sky", "germany", "DE", ""),
    ("Sky Sport Bundesliga 4", "854", "Sky Sport Bundesliga 4", "sky", "germany", "DE", ""),
    ("Sky Sport Bundesliga 5", "855", "Sky Sport Bundesliga 5", "sky", "germany", "DE", ""),
    ("Sky Sport Bundesliga 6", "856", "Sky Sport Bundesliga 6", "sky", "germany", "DE", ""),
    ("Sky Sport Bundesliga 7", "857", "Sky Sport Bundesliga 7", "sky", "germany", "DE", ""),
    ("Sky Sport Bundesliga 8", "858", "Sky Sport Bundesliga 8", "sky", "germany", "DE", ""),
    ("Sky Sport Bundesliga 9", "859", "Sky Sport Bundesliga 9", "sky", "germany", "DE", ""),
    ("Sky Sport Mix", "860", "Sky Sport Mix", "sky", "germany", "DE", ""),
    ("Sky Sport Premier League", "861", "Sky Sport Premier League", "sky", "germany", "DE", ""),
    ("Sky Sport Tennis", "862", "Sky Sport Tennis", "sky", "germany", "DE", ""),
    ("Sky Sport Top Event", "863", "Sky Sport Top Event", "sky", "germany", "DE", ""),
    ("SportDigital Fussball", "864", "SportDigital Fussball", "spor", "germany", "DE", ""),
    ("ZDF", "865", "ZDF", "zdf", "germany", "DE", ""),
    ("ZDF Info", "866", "ZDF Info", "zdf", "germany", "DE", ""),
    ("Sky Sport 1", "871", "Sky Sport 1", "sky", "germany", "AT", ""),
    ("Sky Sport 10", "872", "Sky Sport 10", "sky", "germany", "AT", ""),
    ("Sky Sport 2", "873", "Sky Sport 2", "sky", "germany", "AT", ""),
    ("Sky Sport 3", "874", "Sky Sport 3", "sky", "germany", "AT", ""),
    ("Sky Sport 4", "875", "Sky Sport 4", "sky", "germany", "AT", ""),
    ("Sky Sport 5", "876", "Sky Sport 5", "sky", "germany", "AT", ""),
    ("Sky Sport 6", "877", "Sky Sport 6", "sky", "germany", "AT", ""),
    ("Sky Sport 7", "878", "Sky Sport 7", "sky", "germany", "AT", ""),
    ("Sky Sport 8", "879", "Sky Sport 8", "sky", "germany", "AT", ""),
    ("Sky Sport 9", "880", "Sky Sport 9", "sky", "germany", "AT", ""),
    # --- France ---
    ("Canal", "881", "Canal", "cana", "france", "FR", ""),
    ("Canal Foot", "882", "Canal Foot", "cana", "france", "FR", ""),
    ("Canal Live 10", "883", "Canal Live 10", "cana", "france", "FR", ""),
    ("Canal Live 11", "884", "Canal Live 11", "cana", "france", "FR", ""),
    ("Canal Live 3", "885", "Canal Live 3", "cana", "france", "FR", ""),
    ("Canal Live 4", "886", "Canal Live 4", "cana", "france", "FR", ""),
    ("Canal Live 5", "887", "Canal Live 5", "cana", "france", "FR", ""),
    ("Canal Live 6", "888", "Canal Live 6", "cana", "france", "FR", ""),
    ("Canal Live 7", "889", "Canal Live 7", "cana", "france", "FR", ""),
    ("Canal Live 8", "890", "Canal Live 8", "cana", "france", "FR", ""),
    ("Canal Live 9", "891", "Canal Live 9", "cana", "france", "FR", ""),
    ("Canal Premier League", "892", "Canal Premier League", "cana", "france", "FR", ""),
    ("Canal Sport", "893", "Canal Sport", "cana", "france", "FR", ""),
    ("Canal Sport360", "894", "Canal Sport360", "cana", "france", "FR", ""),
    ("RMC Sport 1", "895", "RMC Sport 1", "rmc", "france", "FR", ""),
    ("RMC Sport 2", "896", "RMC Sport 2", "rmc", "france", "FR", ""),
    ("beIN SPORTS 1", "897", "beIN SPORTS 1", "bein", "france", "FR", ""),
    ("beIN SPORTS 2", "898", "beIN SPORTS 2", "bein", "france", "FR", ""),
    ("beIN SPORTS 3", "899", "beIN SPORTS 3", "bein", "france", "FR", ""),
    ("beIN SPORTS MAX 10", "900", "beIN SPORTS MAX 10", "bein", "france", "FR", ""),
    ("beIN SPORTS MAX 4", "901", "beIN SPORTS MAX 4", "bein", "france", "FR", ""),
    ("beIN SPORTS MAX 5", "902", "beIN SPORTS MAX 5", "bein", "france", "FR", ""),
    ("beIN SPORTS MAX 6", "903", "beIN SPORTS MAX 6", "bein", "france", "FR", ""),
    ("beIN SPORTS MAX 7", "904", "beIN SPORTS MAX 7", "bein", "france", "FR", ""),
    ("beIN SPORTS MAX 8", "905", "beIN SPORTS MAX 8", "bein", "france", "FR", ""),
    ("beIN SPORTS MAX 9", "906", "beIN SPORTS MAX 9", "bein", "france", "FR", ""),
    # --- Spain & Portugal ---
    ("Benfica TV", "911", "Benfica TV", "benf", "iberia", "PT", ""),
    ("Canal 11", "912", "Canal 11", "cana", "iberia", "PT", ""),
    ("DAZN 2", "913", "DAZN 2", "dazn", "iberia", "PT", ""),
    ("DAZN 3", "914", "DAZN 3", "dazn", "iberia", "PT", ""),
    ("DAZN 4", "915", "DAZN 4", "dazn", "iberia", "PT", ""),
    ("DAZN 5", "916", "DAZN 5", "dazn", "iberia", "PT", ""),
    ("DAZN 6", "917", "DAZN 6", "dazn", "iberia", "PT", ""),
    ("Porto Canal", "918", "Porto Canal", "port", "iberia", "PT", ""),
    ("RTP 1", "919", "RTP 1", "rtp", "iberia", "PT", ""),
    ("SIC", "920", "SIC", "sic", "iberia", "PT", ""),
    ("Sport TV", "921", "Sport TV", "spor", "iberia", "PT", ""),
    ("Sport TV 1", "922", "Sport TV 1", "spor", "iberia", "PT", ""),
    ("Sport TV 2", "923", "Sport TV 2", "spor", "iberia", "PT", ""),
    ("Sport TV 3", "924", "Sport TV 3", "spor", "iberia", "PT", ""),
    ("Sport TV 4", "925", "Sport TV 4", "spor", "iberia", "PT", ""),
    ("Sport TV 5", "926", "Sport TV 5", "spor", "iberia", "PT", ""),
    ("Sport TV 6", "927", "Sport TV 6", "spor", "iberia", "PT", ""),
    ("Sport TV 7", "928", "Sport TV 7", "spor", "iberia", "PT", ""),
    ("TVI", "929", "TVI", "tvi", "iberia", "PT", ""),
    ("DAZN F1", "931", "DAZN F1", "dazn", "iberia", "ES", ""),
    ("DAZN LaLiga", "932", "DAZN LaLiga", "dazn", "iberia", "ES", ""),
    ("DAZN LaLiga 2", "933", "DAZN LaLiga 2", "dazn", "iberia", "ES", ""),
    ("Movistar Deportes 1", "934", "Movistar Deportes 1", "movi", "iberia", "ES", ""),
    ("Movistar Deportes 2", "935", "Movistar Deportes 2", "movi", "iberia", "ES", ""),
    ("Movistar Deportes 4", "936", "Movistar Deportes 4", "movi", "iberia", "ES", ""),
    ("Movistar Golf", "937", "Movistar Golf", "movi", "iberia", "ES", ""),
    ("Real Madrid TV", "938", "Real Madrid TV", "real", "iberia", "ES", ""),
    ("Teledeporte", "939", "Teledeporte", "tele", "iberia", "ES", ""),
    ("beIN SPORTS N", "940", "beIN SPORTS N", "bein", "iberia", "ES", ""),
    ("beIN SPORTS XTRA", "941", "beIN SPORTS XTRA", "bein", "iberia", "ES", ""),
    # --- Nordics ---
    ("Canal 9", "951", "Canal 9", "cana", "nordics", "DK", ""),
    ("DR1", "952", "DR1", "dr1", "nordics", "DK", ""),
    ("DR2", "953", "DR2", "dr2", "nordics", "DK", ""),
    ("See", "954", "See", "see", "nordics", "DK", ""),
    ("TV2", "955", "TV2", "tv2", "nordics", "DK", ""),
    ("TV2 Bornholm", "956", "TV2 Bornholm", "tv2", "nordics", "DK", ""),
    ("TV2 Sport", "957", "TV2 Sport", "tv2", "nordics", "DK", ""),
    ("TV2 Sport X", "958", "TV2 Sport X", "tv2", "nordics", "DK", ""),
    ("TV3 Max", "959", "TV3 Max", "tv3", "nordics", "DK", ""),
    ("TV3 Puls", "960", "TV3 Puls", "tv3", "nordics", "DK", ""),
    ("TV3 Sport", "961", "TV3 Sport", "tv3", "nordics", "DK", ""),
    ("TV4 Sportkanalen", "963", "TV4 Sportkanalen", "tv4", "nordics", "SE", ""),
    ("V Sport 1", "964", "V Sport 1", "v", "nordics", "SE", ""),
    ("V Sport Extra", "965", "V Sport Extra", "v", "nordics", "SE", ""),
    ("V Sport Football", "966", "V Sport Football", "v", "nordics", "SE", ""),
    ("V Sport Motor", "967", "V Sport Motor", "v", "nordics", "SE", ""),
    ("V Sport Premium", "968", "V Sport Premium", "v", "nordics", "SE", ""),
    ("V Sport Ultra", "969", "V Sport Ultra", "v", "nordics", "SE", ""),
    # --- Benelux ---
    ("ESPN", "973", "ESPN", "espn", "benelux", "NL", ""),
    ("ESPN 2", "974", "ESPN 2", "espn", "benelux", "NL", ""),
    ("ESPN 3", "975", "ESPN 3", "espn", "benelux", "NL", ""),
    ("Ziggo Sport 2", "976", "Ziggo Sport 2", "zigg", "benelux", "NL", ""),
    ("Ziggo Sport 3", "977", "Ziggo Sport 3", "zigg", "benelux", "NL", ""),
    ("Ziggo Sport 4", "978", "Ziggo Sport 4", "zigg", "benelux", "NL", ""),
    ("Ziggo Sport 5", "979", "Ziggo Sport 5", "zigg", "benelux", "NL", ""),
    ("Ziggo Sport 6", "980", "Ziggo Sport 6", "zigg", "benelux", "NL", ""),
    ("Canvas", "983", "Canvas", "canv", "benelux", "BE", ""),
    # --- Italy ---
    ("Canal 5", "985", "Canal 5", "cana", "italy", "IT", ""),
    ("Euro Sport 1", "986", "Euro Sport 1", "euro", "italy", "IT", ""),
    ("Italia 1", "987", "Italia 1", "ital", "italy", "IT", ""),
    ("Sky Sport Golf", "988", "Sky Sport Golf", "sky", "italy", "IT", ""),
    ("Sky Sport Max", "989", "Sky Sport Max", "sky", "italy", "IT", ""),
    # --- Central & Eastern Europe ---
    ("Canal 360", "991", "Canal 360", "cana", "cee", "PL", ""),
    ("Canal Premium", "992", "Canal Premium", "cana", "cee", "PL", ""),
    ("Canal Sport 2", "993", "Canal Sport 2", "cana", "cee", "PL", ""),
    ("Canal Sport 3", "994", "Canal Sport 3", "cana", "cee", "PL", ""),
    ("Canal Sport 4", "995", "Canal Sport 4", "cana", "cee", "PL", ""),
    ("Canal Sport 5", "996", "Canal Sport 5", "cana", "cee", "PL", ""),
    ("Eleven Sports 1", "997", "Eleven Sports 1", "elev", "cee", "PL", ""),
    ("Eleven Sports 2", "998", "Eleven Sports 2", "elev", "cee", "PL", ""),
    ("Eleven Sports 3", "999", "Eleven Sports 3", "elev", "cee", "PL", ""),
    ("Eleven Sports 4", "1000", "Eleven Sports 4", "elev", "cee", "PL", ""),
    ("Polsat", "1001", "Polsat", "pols", "cee", "PL", ""),
    ("Polsat News", "1002", "Polsat News", "pols", "cee", "PL", ""),
    ("Polsat Sport 2", "1003", "Polsat Sport 2", "pols", "cee", "PL", ""),
    ("Polsat Sport 3", "1004", "Polsat Sport 3", "pols", "cee", "PL", ""),
    ("Polsat Sport Premium 1", "1005", "Polsat Sport Premium 1", "pols", "cee", "PL", ""),
    ("Polsat Sport Premium 2", "1006", "Polsat Sport Premium 2", "pols", "cee", "PL", ""),
    ("TVP Sport", "1007", "TVP Sport", "tvp", "cee", "PL", ""),
    ("Canal Sport", "1011", "Canal Sport", "cana", "cee", "CZ", ""),
    ("Nova Sport 3", "1012", "Nova Sport 3", "nova", "cee", "CZ", ""),
    ("Nova Sport 5", "1013", "Nova Sport 5", "nova", "cee", "CZ", ""),
    ("Diema Sport 2", "1015", "Diema Sport 2", "diem", "cee", "BG", ""),
    ("Diema Sport 3", "1016", "Diema Sport 3", "diem", "cee", "BG", ""),
    ("Euro Sport 1", "1017", "Euro Sport 1", "euro", "cee", "BG", ""),
    ("Euro Sport 2", "1018", "Euro Sport 2", "euro", "cee", "BG", ""),
    ("Max Sport 1", "1019", "Max Sport 1", "max", "cee", "BG", ""),
    ("Max Sport 2", "1020", "Max Sport 2", "max", "cee", "BG", ""),
    ("Max Sport 3", "1021", "Max Sport 3", "max", "cee", "BG", ""),
    ("Max Sport 4", "1022", "Max Sport 4", "max", "cee", "BG", ""),
    ("Nova Sport", "1023", "Nova Sport", "nova", "cee", "BG", ""),
    ("Ring", "1024", "Ring", "ring", "cee", "BG", ""),
    ("bTV", "1025", "bTV", "btv", "cee", "BG", ""),
    ("bTV Action", "1026", "bTV Action", "btv", "cee", "BG", ""),
    ("Digi Sport 1", "1029", "Digi Sport 1", "digi", "cee", "RO", ""),
    ("Digi Sport 2", "1030", "Digi Sport 2", "digi", "cee", "RO", ""),
    ("Digi Sport 3", "1031", "Digi Sport 3", "digi", "cee", "RO", ""),
    ("Digi Sport 4", "1032", "Digi Sport 4", "digi", "cee", "RO", ""),
    ("Prima Sport 1", "1033", "Prima Sport 1", "prim", "cee", "RO", ""),
    ("Prima Sport 4", "1034", "Prima Sport 4", "prim", "cee", "RO", ""),
    # --- Greece & Cyprus ---
    ("Cosmote Sport 1", "1037", "Cosmote Sport 1", "cosm", "greece", "GR", ""),
    ("Cosmote Sport 4", "1038", "Cosmote Sport 4", "cosm", "greece", "GR", ""),
    ("Cosmote Sport 5", "1039", "Cosmote Sport 5", "cosm", "greece", "GR", ""),
    ("Cosmote Sport 6", "1040", "Cosmote Sport 6", "cosm", "greece", "GR", ""),
    ("Cosmote Sport 7", "1041", "Cosmote Sport 7", "cosm", "greece", "GR", ""),
    ("Cosmote Sport 8", "1042", "Cosmote Sport 8", "cosm", "greece", "GR", ""),
    ("Cosmote Sport 9", "1043", "Cosmote Sport 9", "cosm", "greece", "GR", ""),
    ("Nova Sports News", "1044", "Nova Sports News", "nova", "greece", "GR", ""),
    ("Nova Sports Prime", "1045", "Nova Sports Prime", "nova", "greece", "GR", ""),
    ("Nova Sports Start", "1046", "Nova Sports Start", "nova", "greece", "GR", ""),
    ("Cytavision Sports 1", "1049", "Cytavision Sports 1", "cyta", "greece", "CY", ""),
    ("Cytavision Sports 2", "1050", "Cytavision Sports 2", "cyta", "greece", "CY", ""),
    ("Cytavision Sports 3", "1051", "Cytavision Sports 3", "cyta", "greece", "CY", ""),
    ("Cytavision Sports 4", "1052", "Cytavision Sports 4", "cyta", "greece", "CY", ""),
    ("Cytavision Sports 5", "1053", "Cytavision Sports 5", "cyta", "greece", "CY", ""),
    ("Cytavision Sports 6", "1054", "Cytavision Sports 6", "cyta", "greece", "CY", ""),
    ("Cytavision Sports 7", "1055", "Cytavision Sports 7", "cyta", "greece", "CY", ""),
    # --- Russia ---
    ("Match Football 1", "1057", "Match Football 1", "matc", "russia", "RU", ""),
    ("Match Football 2", "1058", "Match Football 2", "matc", "russia", "RU", ""),
    ("Match Football 3", "1059", "Match Football 3", "matc", "russia", "RU", ""),
    ("Match Premier", "1060", "Match Premier", "matc", "russia", "RU", ""),
    ("Match TV", "1061", "Match TV", "matc", "russia", "RU", ""),
    # --- Turkey ---
    ("TRT 1", "1063", "TRT 1", "trt", "turkey", "TR", ""),
    ("TRT 2", "1064", "TRT 2", "trt", "turkey", "TR", ""),
    ("TRT 3", "1065", "TRT 3", "trt", "turkey", "TR", ""),
    ("TRT Spor", "1066", "TRT Spor", "trt", "turkey", "TR", ""),
    ("beIN SPORTS 1", "1067", "beIN SPORTS 1", "bein", "turkey", "TR", ""),
    ("beIN SPORTS 2", "1068", "beIN SPORTS 2", "bein", "turkey", "TR", ""),
    ("beIN SPORTS 3", "1069", "beIN SPORTS 3", "bein", "turkey", "TR", ""),
    ("beIN SPORTS 4", "1070", "beIN SPORTS 4", "bein", "turkey", "TR", ""),
    # --- Latin America ---
    ("Combate", "1071", "Combate", "comb", "latam", "BR", ""),
    ("ESPN", "1072", "ESPN", "espn", "latam", "BR", ""),
    ("ESPN 2", "1073", "ESPN 2", "espn", "latam", "BR", ""),
    ("ESPN 4", "1074", "ESPN 4", "espn", "latam", "BR", ""),
    ("Premiere 1", "1075", "Premiere 1", "prem", "latam", "BR", ""),
    ("Premiere 2", "1076", "Premiere 2", "prem", "latam", "BR", ""),
    ("Premiere 3", "1077", "Premiere 3", "prem", "latam", "BR", ""),
    ("Premiere 4", "1078", "Premiere 4", "prem", "latam", "BR", ""),
    ("Premiere 5", "1079", "Premiere 5", "prem", "latam", "BR", ""),
    ("Premiere 6", "1080", "Premiere 6", "prem", "latam", "BR", ""),
    ("Premiere 7", "1081", "Premiere 7", "prem", "latam", "BR", ""),
    ("TNT", "1082", "TNT", "tnt", "latam", "BR", ""),
    ("ESPN", "1085", "ESPN", "espn", "latam", "AR", ""),
    ("ESPN Premium", "1086", "ESPN Premium", "espn", "latam", "AR", ""),
    ("FOX Sports 2", "1087", "FOX Sports 2", "fox", "latam", "AR", ""),
    ("Tyc Sports", "1088", "Tyc Sports", "tyc", "latam", "AR", ""),
    ("ESPN 2", "1091", "ESPN 2", "espn", "latam", "MX", ""),
    ("ESPN 3", "1092", "ESPN 3", "espn", "latam", "MX", ""),
    ("ESPN 4", "1093", "ESPN 4", "espn", "latam", "MX", ""),
    ("FOX Sports 2", "1094", "FOX Sports 2", "fox", "latam", "MX", ""),
    ("TNT Sports", "1097", "TNT Sports", "tnt", "latam", "CL", ""),
    ("VTV", "1099", "VTV", "vtv", "latam", "UY", ""),
    # --- Canada ---
    ("CP24", "1101", "CP24", "cp24", "canada", "CA", ""),
    ("RDS", "1102", "RDS", "rds", "canada", "CA", ""),
    ("Sportsnet 360", "1103", "Sportsnet 360", "spor", "canada", "CA", ""),
    ("Sportsnet East", "1104", "Sportsnet East", "spor", "canada", "CA", ""),
    ("Sportsnet One", "1105", "Sportsnet One", "spor", "canada", "CA", ""),
    ("Sportsnet Ontario", "1106", "Sportsnet Ontario", "spor", "canada", "CA", ""),
    ("Sportsnet West", "1107", "Sportsnet West", "spor", "canada", "CA", ""),
    ("Sportsnet World", "1108", "Sportsnet World", "spor", "canada", "CA", ""),
    ("TSN 1", "1109", "TSN 1", "tsn", "canada", "CA", ""),
    ("TSN 2", "1110", "TSN 2", "tsn", "canada", "CA", ""),
    ("TSN 3", "1111", "TSN 3", "tsn", "canada", "CA", ""),
    ("TSN 4", "1112", "TSN 4", "tsn", "canada", "CA", ""),
    ("TSN 5", "1113", "TSN 5", "tsn", "canada", "CA", ""),
    ("TVA Sports", "1114", "TVA Sports", "tva", "canada", "CA", ""),
    # --- Australia & NZ ---
    ("Fox Sports 501", "1117", "Fox Sports 501", "fox", "anz", "AU", ""),
    ("Fox Sports 501 Cricket", "1118", "Fox Sports 501 Cricket", "fox", "anz", "AU", ""),
    ("Fox Sports 502", "1119", "Fox Sports 502", "fox", "anz", "AU", ""),
    ("Fox Sports 503", "1120", "Fox Sports 503", "fox", "anz", "AU", ""),
    ("Fox Sports 505", "1121", "Fox Sports 505", "fox", "anz", "AU", ""),
    ("Fox Sports 506", "1122", "Fox Sports 506", "fox", "anz", "AU", ""),
    ("Fox Sports 507", "1123", "Fox Sports 507", "fox", "anz", "AU", ""),
    ("Fox Sports News", "1124", "Fox Sports News", "fox", "anz", "AU", ""),
    ("Stan Sport 10", "1125", "Stan Sport 10", "stan", "anz", "AU", ""),
    ("Stan Sport 11", "1126", "Stan Sport 11", "stan", "anz", "AU", ""),
    ("Stan Sport 12", "1127", "Stan Sport 12", "stan", "anz", "AU", ""),
    ("Stan Sport 13", "1128", "Stan Sport 13", "stan", "anz", "AU", ""),
    ("Stan Sport 14", "1129", "Stan Sport 14", "stan", "anz", "AU", ""),
    ("Stan Sport 15", "1130", "Stan Sport 15", "stan", "anz", "AU", ""),
    ("Stan Sport 16", "1131", "Stan Sport 16", "stan", "anz", "AU", ""),
    ("Stan Sport 18", "1132", "Stan Sport 18", "stan", "anz", "AU", ""),
    ("Stan Sport 19", "1133", "Stan Sport 19", "stan", "anz", "AU", ""),
    ("Stan Sport 2", "1134", "Stan Sport 2", "stan", "anz", "AU", ""),
    ("Stan Sport 3", "1135", "Stan Sport 3", "stan", "anz", "AU", ""),
    ("Stan Sport 4", "1136", "Stan Sport 4", "stan", "anz", "AU", ""),
    ("Stan Sport 5", "1137", "Stan Sport 5", "stan", "anz", "AU", ""),
    ("Stan Sport 6", "1138", "Stan Sport 6", "stan", "anz", "AU", ""),
    ("Stan Sport 7", "1139", "Stan Sport 7", "stan", "anz", "AU", ""),
    ("Stan Sport 9", "1140", "Stan Sport 9", "stan", "anz", "AU", ""),
    ("beIN SPORTS 1", "1141", "beIN SPORTS 1", "bein", "anz", "AU", ""),
    ("Sky Sport 1", "1143", "Sky Sport 1", "sky", "anz", "NZ", ""),
    ("Sky Sport 2", "1144", "Sky Sport 2", "sky", "anz", "NZ", ""),
    ("Sky Sport 3", "1145", "Sky Sport 3", "sky", "anz", "NZ", ""),
    ("Sky Sport 4", "1146", "Sky Sport 4", "sky", "anz", "NZ", ""),
    ("Sky Sport 5", "1147", "Sky Sport 5", "sky", "anz", "NZ", ""),
    ("Sky Sport 6", "1148", "Sky Sport 6", "sky", "anz", "NZ", ""),
    ("Sky Sport 7", "1149", "Sky Sport 7", "sky", "anz", "NZ", ""),
    ("Sky Sport 8", "1150", "Sky Sport 8", "sky", "anz", "NZ", ""),
    ("Sky Sport 9", "1151", "Sky Sport 9", "sky", "anz", "NZ", ""),
    ("Sky Sport Select", "1152", "Sky Sport Select", "sky", "anz", "NZ", ""),
    # --- Middle East ---
    ("Abu Dhabi Sports 1", "1155", "Abu Dhabi Sports 1", "abu", "mideast", "AE", ""),
    ("Starzplay Sports 1", "1156", "Starzplay Sports 1", "star", "mideast", "AE", ""),
    ("Starzplay Sports 2", "1157", "Starzplay Sports 2", "star", "mideast", "AE", ""),
    ("beIN SPORTS 4", "1159", "beIN SPORTS 4", "bein", "mideast", "SA", ""),
    ("beIN SPORTS 5", "1160", "beIN SPORTS 5", "bein", "mideast", "SA", ""),
    ("beIN SPORTS 6", "1161", "beIN SPORTS 6", "bein", "mideast", "SA", ""),
    ("beIN SPORTS 7", "1162", "beIN SPORTS 7", "bein", "mideast", "SA", ""),
    ("beIN SPORTS 8", "1163", "beIN SPORTS 8", "bein", "mideast", "SA", ""),
    ("beIN SPORTS 9", "1164", "beIN SPORTS 9", "bein", "mideast", "SA", ""),
    ("ONE 1", "1167", "ONE 1", "one", "mideast", "IL", ""),
    ("ONE 2", "1168", "ONE 2", "one", "mideast", "IL", ""),
    ("Sport 1", "1169", "Sport 1", "spor", "mideast", "IL", ""),
    ("Sport 2", "1170", "Sport 2", "spor", "mideast", "IL", ""),
    ("Sport 3", "1171", "Sport 3", "spor", "mideast", "IL", ""),
    ("Sport 4", "1172", "Sport 4", "spor", "mideast", "IL", ""),
    ("Sport 5 Gold", "1173", "Sport 5 Gold", "spor", "mideast", "IL", ""),
    ("Sport 5 Live", "1174", "Sport 5 Live", "spor", "mideast", "IL", ""),
    ("Sport 5 Plus", "1175", "Sport 5 Plus", "spor", "mideast", "IL", ""),
    ("Sport 5 Stars", "1176", "Sport 5 Stars", "spor", "mideast", "IL", ""),
]

